domain_path: C:\Users\ishan\internalandddr\internalandddr.vitis\platform-2\export\platform-2\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
